### ISSUE TITLE
Plugin causes XRMToolbox to close completely 

### ISSUE THREAD

**Issue by SteveTe** [MscrmTools/DamSim.SolutionTransferTool#16] opened 2020-03-04 00:43 UTC
After transferring a solution to my QA environment successfully and then changing the destination to the Production environment, XRMtoolbox crashes/close completely after/during the second transfer. No error message is displayed

**Comment by MscrmTools** [comment] 2020-06-05 16:03
I got the same kind of behavior... Will investigate

**Comment by MscrmTools** [comment] 2020-06-09 11:40
As I fixed an issue regarding connections, I'm curious if this issue still occurs? I cannot reproduce

**Comment by SteveTe** [comment] 2020-06-09 12:08
Yes it is still happening.

I've just tried to release from Dev -> QA and then Dev -> Prod. Crashes on the Dev -> Prod

I'm running the following versions:
Solution Transfer Tool: 1.2020.4.10
XrmToolBox: 1.2020.6.40

[cid:image001.png@01D63EAA.6D05D6F0]

Happy to take a video of a transfer now.

Regards,

Steve

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by SteveTe** [comment] 2020-06-09 12:19
Video of when it crashes....

Regards,

Steve

From: Steve Teichert <steve_teichert@hotmail.com>
Sent: Tuesday, 9 June 2020 10:08 PM
To: MscrmTools/DamSim.SolutionTransferTool <reply@reply.github.com>
Subject: RE: [MscrmTools/DamSim.SolutionTransferTool] Plugin causes XRMToolbox to close completely (#16)

Yes it is still happening.

I've just tried to release from Dev -> QA and then Dev -> Prod. Crashes on the Dev -> Prod

I'm running the following versions:

Solution Transfer Tool: 1.2020.4.10
XrmToolBox: 1.2020.6.40

[cid:image001.png@01D63EAB.FAA5D4F0]

Happy to take a video of a transfer now.

Regards,

Steve

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MscrmTools** [comment] 2020-06-09 12:41
@SteveTe   The video is not available in the issue thread...

There is a newer version 1.2020.5.12 that could fix the issue. Can you update the tool and try again?

**Comment by SteveTe** [comment] 2020-06-16 03:56
I’ve re-tested and it is still crashing without any message.

Regards Steve

**Comment by maeg02** [comment] 2020-09-11 10:43
I think I have experienced the same issue, and this is what I got from the log:

Faulting application name: XrmToolBox.exe, version: 1.2020.6.40
Application: XrmToolBox.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(System.__Canon)
   at DamSim.SolutionTransferTool.SolutionTransferTool+<>c__DisplayClass37_1.<Timer_Elapsed>b__5(System.ComponentModel.RunWorkerCompletedEventArgs)
   at XrmToolBox.Extensibility.Worker+<>c__DisplayClass4_0.<WorkAsync>b__0(System.Object, System.ComponentModel.RunWorkerCompletedEventArgs)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(System.ComponentModel.RunWorkerCompletedEventArgs)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


I hope that this helps!

**Comment by Gmanunta81GFPS** [comment] 2021-05-28 12:16
I am sorry to getting in delay with all of you

it is fixed on my side

**Closed** 2024-04-04 08:36 UTC
Labels: bug
